#  Copyright (c) 2022. Justin Vrana - All Rights Reserved
#   You may use, distribute and modify this code under the terms of the MIT license.
# __version__.py
# autogenerated by poetry-hooks 0.1.0

__version__ = "0.1.0"
__title__ = "typecheck"
__authors__ = ["Justin Vrana <justin.vrana@gmail.com>"]
__repository__ = ""
__homepage__ = ""
__description__ = ""
__maintainers__ = ""
__readme__ = ""
__license__ = ""
